---
title: "TTT</br>Flux et champs vectoriel </br>pour la visualisation de matrice OD</br>"
author: "Etienne Côme"
date: "**2020**"
output:
  unilur::tutorial_html_solution:
    toc: true
    toc_float: false
    toc_depth: 1
    suffix: ""
    theme: journal
    highlight: kate
    number_sections: no
    number_subsections: no
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
library(knitr)
library(sf)
library(dplyr)
library(ttt)
## Global options
options(max.print="90")
opts_chunk$set(echo=TRUE,
               cache=FALSE, #TRUE
               prompt=FALSE,
               tidy=FALSE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=90)
options(width = 90)

# no margins
knit_hooks$set(nm = function(before, options, envir){
  if (before){
    par(mar=c(0,0,0,0))
  }
})

# title margins
knit_hooks$set(sm = function(before, options, envir){
  if (before){
    par(mar=c(0,0,1.2,0))
  }
})

# boxes custom
#devtools::install_github("koncina/unilur")
knitr::opts_template$set(alert = list(box.title = "Watch out!",
                                      box.body = list(fill = "#ffe0d9", colour = "black"),
                                      box.header = list(fill = "#FFAD99", colour = "black"),
                                      box.collapse = NULL,
                                      box.icon = "fa-exclamation-triangle"))
knitr::opts_template$set(solution = list(box.title = "Solution",
                                         box.body = list(fill = "#e6f6e7", colour = "black"),
                                         box.header = list(fill = "#ace1af", colour = "black"),
                                         box.icon = "fa-check-square",
                                         box.collapse = TRUE))
knitr::opts_template$set(information = list(box.title = "Information",
                                            box.body = list(fill = "#bbe8f4", colour = "black"),
                                            box.header = list(fill = "#64c9e6", colour = "black"),
                                            box.icon = "fa-info-circle",
                                            box.collapse = NULL))
knitr::opts_template$set(clues = list(box.title = "Indices",
                                      box.body = list(fill = "#fff9dc", colour = "black"),
                                      box.header = list(fill = "#ffec8b", colour = "black"),
                                      box.icon = "fa-search",
                                      box.collapse = TRUE))
```


</br>


# Installation de ttt

```{r, echo=TRUE,eval=FALSE}
remotes::install_github("tributetotobler/ttt")
library(ttt)
library(sf)
library(dplyr)
```

# Exercise 1 : Un exemple historique, les dollars de Tobler

```{block, box.title = "Lire des données", box.body = list(fill = "white"), box.icon = "fa-star"}
Importez les données dollars contenues dans le package `ttt` et regardez leurs structure. 
```


```{block, opts.label = "clues"}
Utilisez `data(dollars)` et `str(dollars)`
```

```{r, solution = TRUE}
data(dollars)
str(dollars)
```
```{block, box.title = "Structure des données", box.body = list(fill = "white"), box.icon = "fa-star"}
Vous devriez avoir dans votre environnement une liste `dollars` avec trois champs  :

- un champ `OD` contenant une matrice OD de taille 12 x 12 contenant des flux
- un champ `polygones` contenant les contours des 12 régions monétaires des USA 
```

```{block, box.title = "Calculez les balances", box.body = list(fill = "white"), box.icon = "fa-star"}
Calculez les balances en chaque nœuds de la matrice OD et stockez le résultats dans une colonne delta de la data.frame polygones.  
```


```{block, opts.label = "clues"}
Utilisez `?rowSums` et `?colSums`
```


```{r, solution=TRUE}
delta = rowSums(dollars$OD)-colSums(dollars$OD)
dollars$polygones$delta=delta
```

```{block, box.title = "Carte +/- ", box.body = list(fill = "white"), box.icon = "fa-star"}
Faire une carte en +/- des balances.
```


```{block, opts.label = "clues"}
Utilisez la fonction `?plus_minus_map`.
```


```{r, echo=FALSE}
plot(st_geometry(dollars$polygones))
plus_minus_map(dollars$polygones,"delta")
```

```{r, solution=TRUE}
plot(st_geometry(dollars$polygones))
plus_minus_map(dollars$polygones,"delta")
```

```{block, box.title = "Calcul du potentiel", box.body = list(fill = "white"), box.icon = "fa-star"}
Calculez le potentiel de poisson de ce jeu de données. 
```


```{block, opts.label = "clues"}
Utilisez la fonction `?poisson.potential`.
```

```{r, solution=TRUE}
pot.dollars = compute_poisson_potential(dollars$polygones,nb_it = 5000)
```

```{block, box.title = "Visualisation du potentiel", box.body = list(fill = "white"), box.icon = "fa-star"}
Regardez la structure de la data.frame retournée et visualisez le champs potentiel stocké dans la colonne `attractivity`.
```


```{block, opts.label = "clues"}
Utilisez la fonction `?str` et `?plot` ou la librairie `ggplot` si vous le souhaitez.
```


```{r, echo=FALSE}
plot(pot.dollars%>% select(attractivity))
```

```{r, solution=TRUE}
str(pot.dollars)
plot(pot.dollars%>% select(attractivity))
```


```{block, box.title = "Visualisation du champ vectoriel", box.body = list(fill = "white"), box.icon = "fa-star"}
Visualisez de manière statique le champ vectoriel calculée à l'aide de la fonction `poisson_flow_map`. N'oubliez pas de régler le paramètre `normfact` pour obtenir quelque chose de lisible.
```



```{r, echo=FALSE}
plot(st_geometry(dollars$polygones))
poisson_flows_map(pot.dollars,normfact=0.01)
```

```{r, solution=TRUE}
plot(st_geometry(dollars$polygones))
poisson_flows_map(pot.dollars,normfact=0.01)
```

# Exercice 2 : Données de migrations résidentielles

```{block, box.title = "Données ", box.body = list(fill = "white"), box.icon = "fa-star"}
Importez les données `FD_MIGCOM_2018AGG.rds` à l'aide de la fonction `readRDS`. Cette data.frame correspond aux données de détails sur les migrations résidentielles française de l’INSEE  [(https://www.insee.fr/fr/statistiques/5395755?sommaire=5395764#dictionnaire)](https://www.insee.fr/fr/statistiques/5395755?sommaire=5395764#dictionnaire). Cette base de données à juste été agrégée pour ne garder qu'un facteur de variation la catégorie socio-professionnelle `CSM` de manière à la rendre un peu plus légère.
```

```{r, solution=TRUE}
migr_agg=readRDS("FD_MIGCOM_2018AGG.rds") 
```


```{block, box.title = "Gestion des arrondissement municipaux", box.body = list(fill = "white"), box.icon = "fa-star"}
Dans cette base, la commune de destination est renseignée avec les codes des arrondissements municipaux pour les villes ayant plusieurs arrondissement. Nous allons commencer par créer une table ou les mouvements sont des mouvements de communes à communes. Pour ce faire, créez à partir de la table précédente une table `com_arr` contenant pour chaque communes ayant des arrondissements le code d'arrondissement (colonne `ARM`) et le code commune (colonne `COMMUNE`). Vous devriez obtenir la table suivante :
```
```{r, echo=FALSE}
com_arr = migr_agg %>% select(COMMUNE,ARM) %>% filter(ARM!="ZZZZZ") %>% distinct()
com_arr
```

```{r, solution=TRUE}
com_arr = migr_agg %>% select(COMMUNE,ARM) %>% filter(ARM!="ZZZZZ") %>% distinct()
```

```{block, box.title = "Gestion des arrondissement municipaux", box.body = list(fill = "white"), box.icon = "fa-star"}
Utilisez cette table pour faire une jointure et récupérez les colonnes :

- COMMUNE : commune de résidence
- COMMUNE_ANM1 : commune de résidence (année n-1)
- CSM : catégorie socio professionnelle
- IPONDI : poids de la ligne
- DEP : département de résidence 
- DEP_ANM1 : département de résidence (année n-1)
```


```{r, solution=TRUE}
migr_com = migr_agg  %>%
  left_join(com_arr,by=c("DCRAN"="ARM")) %>%
  mutate(COMMUNE_ANM1 = if_else(is.na(COMMUNE.y),DCRAN,COMMUNE.y),COMMUNE=COMMUNE.x) %>%
  select(COMMUNE,COMMUNE_ANM1,CSM,IPONDI) %>%
  mutate(DEP_ANM1= substr(COMMUNE_ANM1,1,2),DEP = substr(COMMUNE,1,2))
```

```{block, box.title = "Filtrage", box.body = list(fill = "white"), box.icon = "fa-star"}
Filtrez la table pour ne conserver que :

- les lignes avec CSM == 7
- les lignes ou COMLUNE et COMMUNE_ANM1 diffèrent
- les lignes correspondant à des déménagement de France métropolitaine (hors corse) vers la France métropolitaine (hors corses).
```


```{r, solution=TRUE}
migr_clean = migr_com %>%
  filter(CSM==7) %>%
  filter(COMMUNE!=COMMUNE_ANM1) %>%
  filter(!(DEP %in% c("2A","2B",96:100)),!(DEP_ANM1 %in% c("2A","2B",96:100))) %>%
  arrange(desc(IPONDI))
```

```{block, box.title = "Calcul des balances ", box.body = list(fill = "white"), box.icon = "fa-star"}
Calculez pour chaque communes en utilisant la table précédente :

- le total des flux entrants
- le total des flux sortants
- la balance

```


```{r, solution=TRUE}
migr_in = migr_clean %>% group_by(COMMUNE) %>% summarize(NIN = sum(IPONDI))
migr_out = migr_clean %>% group_by(COMMUNE_ANM1) %>% summarize(NOUT = sum(IPONDI))

delta = migr_in %>% full_join(migr_out,by=c("COMMUNE"="COMMUNE_ANM1")) %>%
  tidyr::replace_na(list(NIN=0,NOUT=0)) %>%
  mutate(delta = NIN-NOUT)
```

```{block, box.title = "Données géographique ", box.body = list(fill = "white"), box.icon = "fa-star"}
Utilisez la fonction  `read_sf` pour charger le fond de carte communal.  
```

```{r, solution=TRUE}
#remotes::install_github("antuki/CARTElette/CARTElette@RPackage")
#library(CARTElette)
#COM <- charger_carte(COG=2020,nivsupra="COM")
#library(sf)
#library(dplyr)
#write_sf(COM,"COM.gpkg")
COM= read_sf("COM.gpkg")
```

```{block, box.title = "Données géographique ", box.body = list(fill = "white"), box.icon = "fa-star"}
Filtrez le fond de carte pour ne conserver que les communes de France métropolitaine (hors corse). Faites la jointure avec votre table contenant les flux entrants, sortants totaux et les balances. Enfin projetez en Lambert 93 (code EPSG 2154).
```


```{r, solution=TRUE}
delta_geo = COM %>%
  filter(!(INSEE_DEP %in% c("2A","2B",971:976))) %>%
  left_join(delta,by=c("INSEE_COM"="COMMUNE")) %>%
  tidyr:: replace_na(list(delta=0)) %>%
  st_transform(2154)
```

```{block, box.title = "Carte des balances", box.body = list(fill = "white"), box.icon = "fa-star"}
Réalisez une carte symbole proportionnelle des balances, la taille des symboles encodera la valeur absolue de la balance et la couleur le signe. Réalisez ensuite une carte en symboles +/-.
```

```{r, echo=FALSE}
delta_dep = delta_geo %>% group_by(INSEE_DEP) %>% summarize(delta=sum(delta)) %>% ungroup() %>% select(delta)
library(ggplot2)
ggplot(delta_dep)+geom_sf() + 
  geom_sf(data=delta_dep %>% st_centroid(),aes(size=abs(delta),color=delta))+
  scale_color_gradient2("Balance")+
  scale_size_area("|Balance|") + 
  theme_minimal() +
  labs(title="Balance départementale des migrations résidentielles",subtitle="des retraités en 2018")
```


```{r, solution=TRUE}
delta_dep = delta_geo %>% group_by(INSEE_DEP) %>% summarize(delta=sum(delta)) %>% ungroup() %>% select(delta)
library(ggplot2)
ggplot(delta_dep)+ 
  geom_sf()+ 
  geom_sf(data=delta_dep %>% st_centroid(),aes(size=abs(delta),color=delta))+
  scale_color_gradient2()
```



```{r, echo=FALSE,fig.width=9,fig.height=9}
plot(delta_dep %>% st_geometry())
plus_minus_map(delta_dep,"delta")
```

```{block, box.title = "Calcul du champ potentiel", box.body = list(fill = "white"), box.icon = "fa-star"}
Calculez le champ potentiel de poisson sur ce jeu de données.
```

```{r, solution=TRUE}
pot = compute_poisson_potential(delta_geo,cellsize = 10000,nb_it = 5000)
```

```{block, box.title = "Calcul du champ potentiel", box.body = list(fill = "white"), box.icon = "fa-star"}
Représentez le champ potentiel et le champ vectoriel.
```

```{r, echo=FALSE}
plot(pot %>% select(attractivity))
```


```{r, solution=TRUE}
plot(pot %>% select(attractivity))
```

```{block, box.title = "Analyse par catgéorie socio-professionelle", box.body = list(fill = "white"), box.icon = "fa-star"}
Reprenez la démarche précédente pour construire et représentez les champs associés à d’autres catégories professionnelles. Vous pouvez également étudier les différences de résultats obtenues lorsque les balances sont calculées en prenant en compte les flux hors de la France métropolitaine.  
```

```{block, box.title = "Droplets", box.body = list(fill = "white"), box.icon = "fa-star"}
Exportez les données associées à un calcul de champ à l'aide de la fonction `jsonlite::write_json` . Utilisez le notebook Observable disponible à l'adresse [https://observablehq.com/@comeetie/ttt-poisson-potential](https://observablehq.com/@comeetie/ttt-poisson-potential) pour l'explorer à l'aide d'une visualisation en droplets. Profitez en pour observez l'influence des paramètres graphiques influençant cette visualisation :

- Nombre de particules
- Vitesse des particules
- Durée de vie des particules
- Coefficient de traînée

```

```{r}
jsonlite::write_json(pot,"./potential_migrfr.json")
```

**reproducibility**

```{r}
sessionInfo()
```

